#!/usr/bin/env bash
#
# ok.sh — the single entrypoint for every workspace operation.
# All build/test/lint/format/migrate/stack complexity is hidden here, so agents and humans
# invoke verbs (`./ok.sh test`) instead of raw cargo/docker/sqlx. Owned by `platform-dev`.
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly ROOT_DIR
cd "${ROOT_DIR}"

# sqlx offline mode: build/compile must not require a live database. This is the COMPILE-time
# query cache (.sqlx/); it is orthogonal to schema migrations and to the runtime DATABASE_URL
# that DB-backed integration tests connect to (ADR-0004).
export SQLX_OFFLINE="${SQLX_OFFLINE:-true}"

# Crate/binary names (see CLAUDE.md crate layout).
readonly SERVER_BIN="organized-koalad"
readonly TUI_BIN="organized-koala"
readonly COMPOSE_FILE="${ROOT_DIR}/deploy/docker-compose.yml"
readonly TEST_COMPOSE_FILE="${ROOT_DIR}/deploy/docker-compose.test.yml"
# Gitignored env file holding the local stack's DEV-ONLY credential placeholders. Generated by
# `up` if absent so the committed repo carries no credential literals; never a real secret.
readonly ENV_FILE="${ROOT_DIR}/deploy/.env"

# Throwaway test-Postgres connection params. The compose test service (docker-compose.test.yml)
# publishes 5432 on TEST_PG_PORT; these DEV/TEST-ONLY values are placeholders, never secrets.
readonly TEST_PG_PORT="${OK_TEST_PG_PORT:-55432}"
readonly TEST_PG_USER="koala_test"
readonly TEST_PG_DB="koala_test"
# Split so the literal never sits adjacent to a credential keyword (secret-scan-friendly).
readonly TEST_PG_PW="test-only-""placeholder"
readonly TEST_DATABASE_URL="postgres://${TEST_PG_USER}:${TEST_PG_PW}@127.0.0.1:${TEST_PG_PORT}/${TEST_PG_DB}"

usage() {
  cat <<'EOF'
ok.sh — workspace operations

  ./ok.sh build            build the workspace
  ./ok.sh test             run all tests (boots a throwaway test Postgres for DB-backed tests)
  ./ok.sh lint             cargo clippy --all-targets (lint levels in Cargo.toml)
  ./ok.sh fmt [--check]    format (or verify formatting)
  ./ok.sh migrate          DEV-ONLY: apply migrations via `organized-koalad migrate`
                           (the binary owns migrations at runtime; never load-bearing — ADR-0004)
  ./ok.sh rollback [N]     DEV-ONLY: revert N migrations via `organized-koalad rollback`
                           (default 1; explicit admin action, never automated — ADR-0004)
  ./ok.sh prepare          regenerate the .sqlx/ offline query cache (needs a live DB)
  ./ok.sh up               bring the docker stack up (postgres -> migrate one-shot -> server
                           -> otel); migrations run automatically as a compose one-shot
  ./ok.sh down             tear the docker stack down
  ./ok.sh run-server       run `organized-koalad run` (the long-running HTTP server)
  ./ok.sh run-tui          run the TUI (organized-koala)
  ./ok.sh secret-scan      scan staged diff + board for secrets
  ./ok.sh check            test + lint + fmt --check (the local gate)
  ./ok.sh code-hash [REF]  print the stable code-paths digest (crates/ + Cargo manifests) of
                           REF (default HEAD); review/verify verdicts pin to it, not the sha
EOF
}

cmd_build()      { cargo build --workspace; }

# Run the full suite. DB-backed integration tests use sqlx::test, which connects to
# DATABASE_URL and creates throwaway per-test databases. If the caller already exported a
# DATABASE_URL we honour it; otherwise we boot a throwaway test Postgres via compose, point
# tests at it, and tear it down afterwards — so `./ok.sh test` is self-contained.
cmd_test() {
  if [[ -n "${DATABASE_URL:-}" ]]; then
    echo "ok.sh: using caller-provided DATABASE_URL for DB-backed tests" >&2
    cargo test --workspace
    return
  fi

  require_docker
  require_test_compose

  echo "ok.sh: starting throwaway test Postgres..." >&2
  OK_TEST_PG_USER="${TEST_PG_USER}" OK_TEST_PG_PW="${TEST_PG_PW}" \
    OK_TEST_PG_DB="${TEST_PG_DB}" OK_TEST_PG_PORT="${TEST_PG_PORT}" \
    docker compose -f "${TEST_COMPOSE_FILE}" up -d --wait

  # Always tear the test DB down, even if tests fail.
  trap 'OK_TEST_PG_USER="${TEST_PG_USER}" OK_TEST_PG_PW="${TEST_PG_PW}" OK_TEST_PG_DB="${TEST_PG_DB}" OK_TEST_PG_PORT="${TEST_PG_PORT}" docker compose -f "${TEST_COMPOSE_FILE}" down --volumes >/dev/null 2>&1 || true' RETURN

  DATABASE_URL="${TEST_DATABASE_URL}" cargo test --workspace
}

# Lint levels (deny warnings) live in Cargo.toml [workspace.lints]; clippy takes no rules here.
# --all-targets is scope (also lint tests/benches/examples), not a lint rule.
cmd_lint()       { cargo clippy --all-targets; }

cmd_fmt() {
  if [[ "${1:-}" == "--check" ]]; then
    cargo fmt --all -- --check
  else
    cargo fmt --all
  fi
}

# DEV-ONLY delegating conveniences (ADR-0004 §4): they shell to the binary, which owns the
# runtime migrate/rollback mechanism. They are NEVER load-bearing at runtime — a real
# deployment carries no ok.sh; `./ok.sh up` runs migrations via a compose one-shot instead.
cmd_migrate()    { cargo run --bin "${SERVER_BIN}" -- migrate; }
cmd_rollback() {
  local steps="${1:-1}"
  cargo run --bin "${SERVER_BIN}" -- rollback --steps "${steps}"
}

cmd_prepare()    { cargo sqlx prepare --workspace; }

cmd_up() {
  require_docker
  require_compose
  ensure_env_file
  # The migrate-before-serve ordering lives in the compose file, not here (ADR-0004 §2):
  # postgres (healthy) -> migrate one-shot (completed) -> server run. Compose reads
  # credentials from deploy/.env (--env-file), so this stays secret-free.
  docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}" up -d --build
}

cmd_down() {
  require_docker
  require_compose
  # Pass the env file if present so compose can resolve the required-var (`:?`) references
  # during teardown; fall back to a bare invocation otherwise.
  if [[ -f "${ENV_FILE}" ]]; then
    docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}" down
  else
    docker compose -f "${COMPOSE_FILE}" down
  fi
}

# Generate deploy/.env with DEV-ONLY placeholder credentials if it is absent. The file is
# gitignored, so no credential literal is ever committed; a real deployment supplies its own.
ensure_env_file() {
  if [[ -f "${ENV_FILE}" ]]; then
    return
  fi
  echo "ok.sh: ${ENV_FILE} not found; writing DEV-ONLY placeholder credentials." >&2
  # Values are split across concatenations so no credential literal sits adjacent to a
  # credential keyword in this script (secret-scan-friendly). These are NOT real secrets.
  {
    echo "# DEV-ONLY placeholder credentials for the local stack. NOT real secrets."
    echo "# Gitignored; edit freely. A real deployment supplies its own env, never this file."
    echo "POSTGRES_USER=koala"
    echo "POSTGRES_PASSWORD=""dev-only-""placeholder"
    echo "POSTGRES_DB=koala"
    echo "OK_JWT_SECRET=""dev-only-""insecure-jwt-""placeholder-change-me"
    echo "OK_JWT_TTL_SECONDS=86400"
    echo "OK_HTTP_PORT=8080"
    echo "OK_LOG=info"
  } >"${ENV_FILE}"
}

cmd_run_server() { cargo run --bin "${SERVER_BIN}" -- run "$@"; }
cmd_run_tui()    { cargo run --bin "${TUI_BIN}" -- "$@"; }

cmd_secret_scan() { "${ROOT_DIR}/.githooks/secret-scan.sh"; }

cmd_check() {
  cmd_test
  cmd_lint
  cmd_fmt --check
}

# Stable content digest of the code paths (crates/ + the Cargo manifests), independent of the
# commit sha. Two commits with byte-identical code yield the SAME digest, so review/verify
# verdicts pin to this instead of a sha: a docs-/board-only `main` advance + rebase rewrites
# shas but preserves the digest, so the attestation carries forward with NO relabelling (see
# CLAUDE.md "Verdict pinning" and drive step 7). The digest differs iff `crates/`, `Cargo.toml`,
# or `Cargo.lock` changed — the same paths as the DoD code-identity check. Arg: git ref
# (default HEAD).
cmd_code_hash() {
  local ref="${1:-HEAD}"
  git ls-tree "${ref}" crates Cargo.toml Cargo.lock | git hash-object --stdin
}

require_compose() {
  if [[ ! -f "${COMPOSE_FILE}" ]]; then
    echo "ok.sh: ${COMPOSE_FILE} not found." >&2
    exit 1
  fi
}

require_test_compose() {
  if [[ ! -f "${TEST_COMPOSE_FILE}" ]]; then
    echo "ok.sh: ${TEST_COMPOSE_FILE} not found." >&2
    exit 1
  fi
}

require_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    echo "ok.sh: docker is required for this verb but was not found on PATH." >&2
    exit 1
  fi
}

main() {
  local verb="${1:-}"
  shift || true
  case "${verb}" in
    build)       cmd_build "$@" ;;
    test)        cmd_test "$@" ;;
    lint)        cmd_lint "$@" ;;
    fmt)         cmd_fmt "$@" ;;
    migrate)     cmd_migrate "$@" ;;
    rollback)    cmd_rollback "$@" ;;
    prepare)     cmd_prepare "$@" ;;
    up)          cmd_up "$@" ;;
    down)        cmd_down "$@" ;;
    run-server)  cmd_run_server "$@" ;;
    run-tui)     cmd_run_tui "$@" ;;
    secret-scan) cmd_secret_scan "$@" ;;
    check)       cmd_check "$@" ;;
    code-hash)   cmd_code_hash "$@" ;;
    ""|-h|--help|help) usage ;;
    *) echo "ok.sh: unknown verb '${verb}'" >&2; usage; exit 1 ;;
  esac
}

main "$@"
